using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;

static class Reflector
{
    static string getAssembly(Type type)
    {
        Assembly assembly = type.Assembly;
        return assembly.FullName;
    }

    static bool getConstructors(Type type) { return type.GetConstructors().Length>0; }
    static IEnumerable<string> getMethods(Type type)
    {
        return type.GetMethods().Select(p=>p.Name);
    }

    static IEnumerable<string> getPropertiesFields(Type type) { 
        var fields = type.GetFields().Select(p=>p.Name);
        var properties = type.GetProperties().Select(p=>p.Name);
        return fields.Concat(properties);
    }

    static IEnumerable<string> getInterfaces(Type type)
    {
       return type.GetInterfaces().Select(p => p.Name);
    }

    static IEnumerable<string> getParamFromType(Type type, Type param_type)
    {
        return type.GetMethods().Where(m=>m.GetParameters().Any(p=>p.ParameterType==param_type)).Select(m=>m.Name);
    }

    static void writeInFile(IEnumerable<string> ienum)
    {
        File.AppendAllLines(@"C:\Из рабочего стола\Labs 3 sem\OOP\Lab#11\info.txt", ienum);
    }

    static void InvokeFromFile(Type type, string methodName, string filePath)
    {
        MethodInfo method = type.GetMethod(methodName);

        var parameters = method.GetParameters();
        string[] lines = File.ReadAllLines(filePath);
        object[] args = new object[parameters.Length];

        for (int i = 0; i < parameters.Length; i++)
        {
            Type paramType = parameters[i].ParameterType;
            args[i] = Convert.ChangeType(lines[i], paramType);
        }

        method.Invoke(type, args);
    }

    static T Create<T>()
    {

        Type type = typeof(T);

        ConstructorInfo[] constructors = type.GetConstructors();
        try
        {
            if (constructors.Length == 0) throw new InvalidOperationException("Нет конструкторов!");
        }
        catch (InvalidOperationException e)
        {
            Console.WriteLine(e.Message);
        }
        var constructor = constructors[0];
        var parameters = constructor.GetParameters();

        if (parameters.Length == 0) return (T)Activator.CreateInstance(type);

        object[] args = parameters.Select(p => GenerateValue(p.ParameterType)).ToArray();

        return (T)Activator.CreateInstance(type, args);


    }

    private static object GenerateValue(Type t)
    {
        Random rnd = new Random();
        if (t == typeof(int)) return rnd.Next(1, 100);
        if (t == typeof(double)) return rnd.NextDouble() * 100;
        if (t == typeof(string)) return "AutoGeneratedString";
        if (t == typeof(bool)) return rnd.Next(2) == 0;
        if (t.IsEnum) return Enum.GetValues(t).GetValue(0);
        if (t.IsClass && t.GetConstructor(Type.EmptyTypes) != null)
            return Activator.CreateInstance(t);
        return null;
    }


}
